services:
  - type: web
    name: nids-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: nids-app
          property: port
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
